In [ ]:
# convert hex representation to np.float16
import numpy as np

hex_input = "0x3c00"
hex_input = "0xad1e"
float16_value = np.frombuffer(np.array([int(hex_input, 16)], dtype=np.uint16).tobytes(), dtype=np.float16)[0]
print(float16_value)



-0.07996


In [ ]:
def hex_to_float16(hex_str):
    """
    Convert a hexadecimal representation to numpy float16
    
    Args:
        hex_str: String containing hex value (with or without '0x' prefix)
        
    Returns:
        numpy.float16 value
    """
    # Handle '0x' prefix if present
    if hex_str.startswith('0x') or hex_str.startswith('0X'):
        hex_str = hex_str[2:]
    
    # Convert hex to integer
    int_val = int(hex_str, 16)
    
    # Create a uint16 array with the integer value
    uint16_array = np.array([int_val], dtype=np.uint16)
    
    # View the uint16 array as float16
    float16_val = uint16_array.view(np.float16)[0]
    
    return float16_val

# Example usage:
hex_input = "0x1bf5 0xa432 0x18d6 0x1e7a 0x24d1 0x1d3d 0x1e3a 0xa60d 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000"  # Hexadecimal representation of 1.0 in float16
# split the hex string into individual hex values
hex_input = hex_input.split()
result = hex_to_float16(hex_input)
print(f"Hex: {hex_input} → Float16: {result}")

ValueError: invalid literal for int() with base 16: '1bf5 0xa432 0x18d6 0x1e7a 0x24d1 0x1d3d 0x1e3a 0xa60d 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000'

In [138]:
hex_input = "0x18d6"  # Hexadecimal representation of 1.0 in float16
result = hex_to_float16(hex_input)
print(f"Hex: {hex_input} → Float16: {result}")

Hex: 0x18d6 → Float16: 0.002361297607421875


In [ ]:
0x1bf5 0xa432 0x18d6 0x1e7a 0x24d1 0x1d3d 0x1e3a 0xa60d 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000

In [109]:
A = np.array([0.01]*15, dtype=np.float16)
B = np.ones((15, 8), dtype=np.float16) * (-2)
B = B.astype(np.float16)
C = np.zeros((8, 8), dtype=np.float16)
# write a matrix multiplication with intermediate results in float16
for i in range(15):
    for j in range(8):
        for k in range(8):
            C[j, k] += np.multiply(A[i], B[i, j], dtype=np.float16).astype(np.float16)
print(C)


[[-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]]


In [114]:
import torch

# Create tensors with float16 precision
A = torch.full((1,15), 0.01, dtype=torch.float16).half()
B = torch.full((15, 8), -2.0, dtype=torch.float16).half()
C = torch.zeros((8, 8), dtype=torch.float16)

C = torch.mm(A, B)
print(C)

tensor([[-0.3000, -0.3000, -0.3000, -0.3000, -0.3000, -0.3000, -0.3000, -0.3000]],
       dtype=torch.float16)


In [ ]:
[[-0.001243 -0.00602  -0.001615 -0.001265 -0.002384  0.005123 -0.002161
   0.003744]]
in_token:  [ 0.00529   0.004227 -0.013596 ... -0.001266 -0.003633  0.00779 ]
gate_weights:  [-0.0151   -0.002773  0.00969  ...  0.004692 -0.01395   0.003733]
expert_w1_weights:  0.01733
expert_w1_bias:  1.0
expert_w2_weights:  -0.00224
experts_w2_bias:  0.0184
expert_w3_weights:  -0.0066
expert_w3_bias:  0.003206
actual_out:  [0. 0. 0. ... 0. 0. 0.]
golden:  [ 0.02798   0.01973   0.01189  ...  0.0116   -0.01367   0.000677]
in_token_address:  0xc0000000
gate_weights_address:  0xc0000800
expert_w1_weights_address:  0xc0004800
expert_w1_bias_address:  0xc0904800
expert_w2_weights_address:  0xc0906c00
expert_w2_bias_address:  0xc1206c00
expert_w3_weights_address:  0xc120b400
expert_w3_bias_address:  0xc1b0b400
actual_out_address:  0xc1b0d800
golden_address:  0xc1b0e000

In [ ]:
[Check Preload] Addresses
in_token: 0xc0000000
gate_weight: 0xc0000800
expert_w1_weight: 0xc0004800
expert_w1_bias: 0xc0904800
expert_w2_weight: 0xc0906c00
expert_w2_bias: 0xc1206c00
expert_w3_weight: 0xc120b400
expert_w3_bias: 0xc1b0b400
actual: 0xc1b0d800
golden: 0xc1b0e000
n_token: 1
dim: 1024
inter_dim: 512
n_routed_experts: 8
[Check Preload] with first 8 elements of each row of the input
in_token:
    0x3c00 0x4000 0x2103 0x25bd 0x24c8 0xa101 0x20dd 0x9633 0x943a 0x1c34 0x15e6 0x2372 0x1fcb 0x14fc 0x1c8c 0x1ad5 
gate_weights:
    0x2462 0xa00e 0xa15a 0xa18e 0x21b8 0x9d50 0x9fb8 0x15a4 
    0x983d 0x9ef2 0x1fb9 0x2174 0x210b 0x1fda 0x1c1f 0xa48c 
expert_w1_weights:
    0xa2a2 0x1fe9 0x9150 0xa259 0x244f 0x21d6 0xa3d0 0x202d 0xa220 0xa3f0 0x9e2e 0x9e3b 0xa17c 0x94e5 0x0899 0xa11a 
expert_w1_bias:
    0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 0x3c00 
expert_w3_weights:
    0xa03a 0x0f03 0x1bb2 0x214e 0x2043 0xa447 0x9be8 0xa1f0 0x2571 0xa1ce 0x9bc7 0x2042 0x20aa 0xa00e 0xa010 0x9d3b 
actual_out:
    0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 
golden_out:
    0x9c38 0xa744 0x2090 0xa388 0x1c91 0x212e 0xa5c2 0xa1d6 0xa0d0 0x9aba 0x1990 0x28f2 0x9a6c 0x210c 0xa8f9 0xa2e7 